export const IMG_CDN_URL =
	"https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/";

export const IMG_SLIDER_URL =
	"https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_520,h_520/";
export const Restaurant_Data = [
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "326429",
			name: "Punjabi Angithi",
			uuid: "c0119f1a-7c13-4dac-a384-73fcf01be291",
			city: "4",
			area: "Ashok Vihar",
			totalRatingsString: "1000+ ratings",
			cloudinaryImageId: "lgfkquq3npd3r9oiy62b",
			cuisines: ["North Indian", "Chinese", "Punjabi", "Snacks"],
			tags: [],
			costForTwo: 40000,
			costForTwoString: "₹400 FOR TWO",
			deliveryTime: 36,
			minDeliveryTime: 36,
			maxDeliveryTime: 36,
			slaString: "36 MINS",
			lastMileTravel: 5.5,
			slugs: {
				restaurant: "punjabi-angithi-ashok-vihar-ashok-vihar",
				city: "delhi",
			},
			cityState: "4",
			address:
				"Shop NO. 27, Ground floor, Satyawati Colony, Ashok Vihar, Phase 3, Delhi",
			locality: "Satyawati Colony",
			parentId: 4464,
			unserviceable: false,
			veg: true,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "Flat ₹150 off",
				shortDescriptionList: [
					{
						meta: "Flat ₹150 off on orders above ₹499",
						discountType: "Flat",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "Flat ₹150 off on orders above ₹499 | Use code FLAT150",
						discountType: "Flat",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "₹150 OFF",
				shortDescriptionList: [
					{
						meta: "Use FLAT150",
						discountType: "Flat",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "Flat ₹150 off on orders above ₹499 | Use code FLAT150",
						discountType: "Flat",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			ribbon: [
				{
					type: "PROMOTED",
				},
			],
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "cid=5687244~p=1~eid=00000185-9f7f-f12c-24f7-44be0022015a",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "5.5 kms",
			hasSurge: false,
			sla: {
				restaurantId: "326429",
				deliveryTime: 36,
				minDeliveryTime: 36,
				maxDeliveryTime: 36,
				lastMileTravel: 5.5,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: true,
			avgRating: "4.1",
			totalRatings: 1000,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "253784",
			name: "McDonald's",
			uuid: "4d341464-8c13-4a0f-88ac-f707af01e632",
			city: "4",
			area: "Delhi",
			totalRatingsString: "1000+ ratings",
			cloudinaryImageId: "opribt7sjqq712icbby9",
			cuisines: ["American"],
			tags: [],
			costForTwo: 40000,
			costForTwoString: "₹400 FOR TWO",
			deliveryTime: 21,
			minDeliveryTime: 21,
			maxDeliveryTime: 21,
			slaString: "21 MINS",
			lastMileTravel: 1,
			slugs: {
				restaurant: "mcdonalds-delhi-shalimar-bagh-ashok-vihar",
				city: "delhi",
			},
			cityState: "4",
			address:
				"Delhi Shalimar Bagh,  Plot No- 2, B Block Community Center, Shalimar Bagh.,New Delhi- 110088",
			locality: "Shalimar Bagh",
			parentId: 630,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "20% off",
				shortDescriptionList: [
					{
						meta: "20% off | Use SWIGGYIT",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "20% off up to ₹50 | Use code SWIGGYIT",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "20% OFF",
				shortDescriptionList: [
					{
						meta: "Use SWIGGYIT",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "20% off up to ₹50 | Use code SWIGGYIT",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "1 kms",
			hasSurge: false,
			sla: {
				restaurantId: "253784",
				deliveryTime: 21,
				minDeliveryTime: 21,
				maxDeliveryTime: 21,
				lastMileTravel: 1,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "4.2",
			totalRatings: 1000,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "550729",
			name: "The Burger Club",
			uuid: "92a004ad-c418-4ffc-a01c-1fe30d333fe3",
			city: "4",
			area: "Shalimar Bagh",
			totalRatingsString: "500+ ratings",
			cloudinaryImageId: "cc4hlzukqocjvzzl4ewh",
			cuisines: ["American", "Beverages", "Desserts"],
			tags: [],
			costForTwo: 25000,
			costForTwoString: "₹250 FOR TWO",
			deliveryTime: 24,
			minDeliveryTime: 24,
			maxDeliveryTime: 24,
			slaString: "24 MINS",
			lastMileTravel: 1,
			slugs: {
				restaurant: "the-burger-club-ashok-vihar-ashok-vihar",
				city: "delhi",
			},
			cityState: "4",
			address:
				"Plot No. 2, B Block, Block BD, West Shalimar Bagh, COMMUNITY CENTER, New Delhi, North West Delhi, Delhi, 110088",
			locality: "Block Bd",
			parentId: 2285,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "50% off",
				shortDescriptionList: [
					{
						meta: "50% off | Use GUILTFREEJAN",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹125 | Use code GUILTFREEJAN",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "50% OFF",
				shortDescriptionList: [
					{
						meta: "Use GUILTFREEJAN",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹125 | Use code GUILTFREEJAN",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "1 kms",
			hasSurge: false,
			sla: {
				restaurantId: "550729",
				deliveryTime: 24,
				minDeliveryTime: 24,
				maxDeliveryTime: 24,
				lastMileTravel: 1,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "4.0",
			totalRatings: 500,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "36279",
			name: "Bille Di hatti (Pitampura) ",
			uuid: "a7e53533-9300-46e7-9e6b-ba3278903701",
			city: "4",
			area: "Pitampura",
			totalRatingsString: "1000+ ratings",
			cloudinaryImageId: "xovqdwufznyil35jg602",
			cuisines: ["Street Food", "Snacks", "North Indian"],
			tags: [],
			costForTwo: 10000,
			costForTwoString: "₹100 FOR TWO",
			deliveryTime: 27,
			minDeliveryTime: 27,
			maxDeliveryTime: 27,
			slaString: "27 MINS",
			lastMileTravel: 3,
			slugs: {
				restaurant: "bille-di-hatti-pp-trade-centre-nsp",
				city: "delhi",
			},
			cityState: "4",
			address: "Rp 8 Pitampura new delhi -110034",
			locality: "RP Block, Pitampura",
			parentId: 4639,
			unserviceable: false,
			veg: true,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "FLAT125 off",
				shortDescriptionList: [
					{
						meta: "FLAT125 off | Use FLATDEAL",
						discountType: "Flat",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "FLAT125 off | Use FLATDEAL",
						discountType: "Flat",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "₹125 OFF",
				shortDescriptionList: [
					{
						meta: "Use FLATDEAL",
						discountType: "Flat",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "FLAT125 off | Use FLATDEAL",
						discountType: "Flat",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			ribbon: [
				{
					type: "PROMOTED",
				},
			],
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "cid=5701404~p=4~eid=00000185-9f7f-f12c-24f7-44bf00220459",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "3 kms",
			hasSurge: false,
			sla: {
				restaurantId: "36279",
				deliveryTime: 27,
				minDeliveryTime: 27,
				maxDeliveryTime: 27,
				lastMileTravel: 3,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: true,
			avgRating: "4.0",
			totalRatings: 1000,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "10208",
			name: "Burger King",
			uuid: "3990e893-8191-4fbf-a00c-3b680986be90",
			city: "4",
			area: "Rohini",
			totalRatingsString: "1000+ ratings",
			cloudinaryImageId: "bzqbcsgccpkufrnljmfo",
			cuisines: ["Burgers", "American"],
			tags: [],
			costForTwo: 35000,
			costForTwoString: "₹350 FOR TWO",
			deliveryTime: 34,
			minDeliveryTime: 34,
			maxDeliveryTime: 34,
			slaString: "34 MINS",
			lastMileTravel: 5.900000095367432,
			slugs: {
				restaurant: "burger-king-d-mall-twin-district-center-rohini",
				city: "delhi",
			},
			cityState: "4",
			address:
				"Unit 21-24, Ground Floor, D Mall, Twin District Center, Rohini, New Delhi",
			locality: "D Mall, Twin District Center",
			parentId: 166,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "Get every item under 129",
				shortDescriptionList: [
					{
						meta: "Get every item under 129",
						discountType: "FinalPrice",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "Get every item under 129",
						discountType: "FinalPrice",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "",
				shortDescriptionList: [
					{
						meta: "",
						discountType: "FinalPrice",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "Get every item under 129",
						discountType: "FinalPrice",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			ribbon: [
				{
					type: "PROMOTED",
				},
			],
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "cid=5711268~p=19~eid=00000185-9f7f-f12c-24f7-44c400221303",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "5.9 kms",
			hasSurge: false,
			sla: {
				restaurantId: "10208",
				deliveryTime: 34,
				minDeliveryTime: 34,
				maxDeliveryTime: 34,
				lastMileTravel: 5.900000095367432,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: true,
			avgRating: "4.2",
			totalRatings: 1000,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "20046",
			name: "Everbake",
			uuid: "67f8419a-8723-46de-bd22-910023260dde",
			city: "4",
			area: "Shalimar Bagh",
			totalRatingsString: "5000+ ratings",
			cloudinaryImageId: "au28pqexqycnlmskk8bl",
			cuisines: ["North Indian", "Snacks", "Desserts"],
			tags: [],
			costForTwo: 50000,
			costForTwoString: "₹500 FOR TWO",
			deliveryTime: 17,
			minDeliveryTime: 17,
			maxDeliveryTime: 17,
			slaString: "17 MINS",
			lastMileTravel: 1.899999976158142,
			slugs: {
				restaurant: "ever-bake-shalimar-bagh-nsp",
				city: "delhi",
			},
			cityState: "4",
			address: "BN-2, Central Market, Shalimar Bagh, New Delhi",
			locality: "Central Market",
			parentId: 4772,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "20% off",
				shortDescriptionList: [
					{
						meta: "20% off | Use SWIGGYIT",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "20% off up to ₹50 | Use code SWIGGYIT",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "20% OFF",
				shortDescriptionList: [
					{
						meta: "Use SWIGGYIT",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "20% off up to ₹50 | Use code SWIGGYIT",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "1.8 kms",
			hasSurge: false,
			sla: {
				restaurantId: "20046",
				deliveryTime: 17,
				minDeliveryTime: 17,
				maxDeliveryTime: 17,
				lastMileTravel: 1.899999976158142,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "4.3",
			totalRatings: 5000,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "34466",
			name: "Apni Rasoi (Sector-8)",
			uuid: "2ba5fe88-ff16-487f-b18f-b2a6b8664adb",
			city: "4",
			area: "Sector 8, Rohini",
			totalRatingsString: "100+ ratings",
			cloudinaryImageId: "rnyltb1hjq1sktcle3mj",
			cuisines: ["North Indian"],
			tags: [],
			costForTwo: 25000,
			costForTwoString: "₹250 FOR TWO",
			deliveryTime: 25,
			minDeliveryTime: 25,
			maxDeliveryTime: 25,
			slaString: "25 MINS",
			lastMileTravel: 4.5,
			slugs: {
				restaurant: "apni-rasoi-sector-8-rohini-rohini",
				city: "delhi",
			},
			cityState: "4",
			address: "B-6/150, Sector 8, Rohini, New Delhi",
			locality: "Sector 8",
			parentId: 64,
			unserviceable: false,
			veg: true,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "30% off",
				shortDescriptionList: [
					{
						meta: "30% off | Use JUMBO",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "30% off up to ₹150 on orders above ₹479 | Use code JUMBO",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "30% OFF",
				shortDescriptionList: [
					{
						meta: "Use JUMBO",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "30% off up to ₹150 on orders above ₹479 | Use code JUMBO",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			ribbon: [
				{
					type: "PROMOTED",
				},
			],
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "cid=5708099~p=7~eid=00000185-9f7f-f12c-24f7-44c000220722",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "4.5 kms",
			hasSurge: false,
			sla: {
				restaurantId: "34466",
				deliveryTime: 25,
				minDeliveryTime: 25,
				maxDeliveryTime: 25,
				lastMileTravel: 4.5,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: true,
			avgRating: "4.2",
			totalRatings: 100,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "508851",
			name: "Pizza Hut",
			uuid: "2ce87c7e-12b0-4674-aff3-6927ef694063",
			city: "4",
			area: "Adarsh Nagar",
			totalRatingsString: "100+ ratings",
			cloudinaryImageId: "chijnq5wnvzigtlx7wvt",
			cuisines: ["Pizzas"],
			tags: [],
			costForTwo: 35000,
			costForTwoString: "₹350 FOR TWO",
			deliveryTime: 27,
			minDeliveryTime: 27,
			maxDeliveryTime: 27,
			slaString: "27 MINS",
			lastMileTravel: 2.5,
			slugs: {
				restaurant: "pizza-hut-adarsh-nagar-gtb-nagar",
				city: "delhi",
			},
			cityState: "4",
			address:
				"PIZZA HUT at Ground Floor, B-45, Rajan Babu Road, Adarsh Nagar, MODEL TOWN, North,Delhi, 110033",
			locality: "Rajan Babu Road",
			parentId: 721,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "50% off",
				shortDescriptionList: [
					{
						meta: "50% off | Use TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹100 | Use code TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "50% OFF",
				shortDescriptionList: [
					{
						meta: "Use TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹100 | Use code TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "2.5 kms",
			hasSurge: false,
			sla: {
				restaurantId: "508851",
				deliveryTime: 27,
				minDeliveryTime: 27,
				maxDeliveryTime: 27,
				lastMileTravel: 2.5,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "3.8",
			totalRatings: 100,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "28961",
			name: "Gulab Wala",
			uuid: "11dedb69-0153-45b9-b4bd-129212bb9480",
			city: "4",
			area: "Main Road",
			totalRatingsString: "5000+ ratings",
			cloudinaryImageId: "d1ham4g7azt62xzvghfg",
			cuisines: ["North Indian", "Sweets", "South Indian"],
			tags: [],
			costForTwo: 35000,
			costForTwoString: "₹350 FOR TWO",
			deliveryTime: 28,
			minDeliveryTime: 28,
			maxDeliveryTime: 28,
			slaString: "28 MINS",
			lastMileTravel: 3,
			slugs: {
				restaurant: "gulab-wala-pitampura-nsp",
				city: "delhi",
			},
			cityState: "4",
			address: "5, Main Road, Pitampura, New Delhi",
			locality: "Main Road",
			parentId: 3645,
			unserviceable: false,
			veg: true,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "20% off",
				shortDescriptionList: [
					{
						meta: "20% off | Use MISSEDYOU",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "20% off up to ₹50 | Use code MISSEDYOU",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "20% OFF",
				shortDescriptionList: [
					{
						meta: "Use MISSEDYOU",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "20% off up to ₹50 | Use code MISSEDYOU",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "3 kms",
			hasSurge: false,
			sla: {
				restaurantId: "28961",
				deliveryTime: 28,
				minDeliveryTime: 28,
				maxDeliveryTime: 28,
				lastMileTravel: 3,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "4.3",
			totalRatings: 5000,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "126002",
			name: "Maruti Tiffins",
			uuid: "31cad900-67ce-41a0-990f-05ab47dc2463",
			city: "4",
			area: "Shalimar Bagh",
			totalRatingsString: "100+ ratings",
			cloudinaryImageId: "rzxig99mbj6ki6kshq2r",
			cuisines: ["North Indian"],
			tags: [],
			costForTwo: 12000,
			costForTwoString: "₹120 FOR TWO",
			deliveryTime: 29,
			minDeliveryTime: 29,
			maxDeliveryTime: 29,
			slaString: "29 MINS",
			lastMileTravel: 2.299999952316284,
			slugs: {
				restaurant: "maruti-tiffins-ashok-vihar",
				city: "delhi",
			},
			cityState: "4",
			address: "AG 450, first floor, back side entry, Shalimar Bagh",
			locality: "Ashok Vihar",
			parentId: 132812,
			unserviceable: false,
			veg: true,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "15% off",
				shortDescriptionList: [
					{
						meta: "15% off on all orders",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "15% off on all orders",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "15% OFF",
				shortDescriptionList: [
					{
						meta: "",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "15% off on all orders",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			ribbon: [
				{
					type: "PROMOTED",
				},
			],
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "cid=5659485~p=10~eid=00000185-9f7f-f12c-24f7-44c100220a23",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "2.2 kms",
			hasSurge: false,
			sla: {
				restaurantId: "126002",
				deliveryTime: 29,
				minDeliveryTime: 29,
				maxDeliveryTime: 29,
				lastMileTravel: 2.299999952316284,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: true,
			avgRating: "4.2",
			totalRatings: 100,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "513404",
			name: "KFC",
			uuid: "6d800b0a-0622-4c40-8637-d54f2d6a1a26",
			city: "4",
			area: "Shalimar Bagh",
			totalRatingsString: "100+ ratings",
			cloudinaryImageId: "bdcd233971b7c81bf77e1fa4471280eb",
			cuisines: ["American", "Snacks", "Biryani"],
			tags: [],
			costForTwo: 40000,
			costForTwoString: "₹400 FOR TWO",
			deliveryTime: 28,
			minDeliveryTime: 28,
			maxDeliveryTime: 28,
			slaString: "28 MINS",
			lastMileTravel: 1,
			slugs: {
				restaurant: "kfc-shalimar-bagh-shalimar-bagh",
				city: "delhi",
			},
			cityState: "4",
			address:
				"Shop Number 24 & 25,Ground floor, plot number 2, Block b, community center,Block BD. West Shalimar Bagh New Delhi 110088.",
			locality: "Block BD",
			parentId: 547,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "20% off",
				shortDescriptionList: [
					{
						meta: "20% off | Use SWIGGYIT",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "20% off up to ₹50 | Use code SWIGGYIT",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "20% OFF",
				shortDescriptionList: [
					{
						meta: "Use SWIGGYIT",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "20% off up to ₹50 | Use code SWIGGYIT",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "1 kms",
			hasSurge: false,
			sla: {
				restaurantId: "513404",
				deliveryTime: 28,
				minDeliveryTime: 28,
				maxDeliveryTime: 28,
				lastMileTravel: 1,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "3.7",
			totalRatings: 100,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "43409",
			name: "Madras Dosa & Chinese Corner (Shalimar Bagh)",
			uuid: "396d92a0-a461-45ab-9b09-2b406c6d02fb",
			city: "4",
			area: "Shalimar Bagh",
			totalRatingsString: "500+ ratings",
			cloudinaryImageId: "no1tq6ppotajav2rvjpd",
			cuisines: ["South Indian", "Indian", "Snacks"],
			tags: [],
			costForTwo: 30000,
			costForTwoString: "₹300 FOR TWO",
			deliveryTime: 24,
			minDeliveryTime: 24,
			maxDeliveryTime: 24,
			slaString: "24 MINS",
			lastMileTravel: 2.4000000953674316,
			slugs: {
				restaurant: "madras-dosa-and-chinese-corner-shalimar-bagh-ashok-vihar",
				city: "delhi",
			},
			cityState: "4",
			address: "11, Near AL Market, Shalimar Bagh, New Delhi",
			locality: "AL Market Shalimar Bagh",
			parentId: 6777,
			unserviceable: false,
			veg: true,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "2.4 kms",
			hasSurge: false,
			sla: {
				restaurantId: "43409",
				deliveryTime: 24,
				minDeliveryTime: 24,
				maxDeliveryTime: 24,
				lastMileTravel: 2.4000000953674316,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "3.9",
			totalRatings: 500,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "32550",
			name: "Spice Sea",
			uuid: "bbdf25bd-a612-4466-a1dd-bc8939e8806c",
			city: "4",
			area: "Cc Block Market",
			totalRatingsString: "100+ ratings",
			cloudinaryImageId: "c8cyyagtcsmnfl2ejyhe",
			cuisines: ["North Indian", "Chinese"],
			tags: [],
			costForTwo: 60000,
			costForTwoString: "₹600 FOR TWO",
			deliveryTime: 21,
			minDeliveryTime: 21,
			maxDeliveryTime: 21,
			slaString: "21 MINS",
			lastMileTravel: 0.4000000059604645,
			slugs: {
				restaurant: "spice-sea-shalimar-bagh-ashok-vihar",
				city: "delhi",
			},
			cityState: "4",
			address: "C 19-20-21, CC Block Market, Shalimar Bagh, New Delhi",
			locality: "Shalimar Bagh",
			parentId: 16665,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "0.4 kms",
			hasSurge: false,
			sla: {
				restaurantId: "32550",
				deliveryTime: 21,
				minDeliveryTime: 21,
				maxDeliveryTime: 21,
				lastMileTravel: 0.4000000059604645,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "4.1",
			totalRatings: 100,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "50887",
			name: "Mr. Crust Bakers",
			uuid: "10644613-e966-425c-8e6f-49c2a6959fcc",
			city: "4",
			area: "Phase 1",
			totalRatingsString: "1000+ ratings",
			cloudinaryImageId: "bt5wtmmqndnxryrhw1nr",
			cuisines: ["Desserts", "Bakery", "Sweets"],
			tags: [],
			costForTwo: 30000,
			costForTwoString: "₹300 FOR TWO",
			deliveryTime: 30,
			minDeliveryTime: 30,
			maxDeliveryTime: 30,
			slaString: "30 MINS",
			lastMileTravel: 4.400000095367432,
			slugs: {
				restaurant: "mr-crust-bakers-phase-1-ashok-vihar",
				city: "delhi",
			},
			cityState: "4",
			address: "KD 57-A, Ashok Vihar Phase 1, New Delhi",
			locality: "Ashok Vihar",
			parentId: 13682,
			unserviceable: false,
			veg: true,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "20% off",
				shortDescriptionList: [
					{
						meta: "20% off | Use TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "20% off up to ₹50 | Use code TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "20% OFF",
				shortDescriptionList: [
					{
						meta: "Use TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "20% off up to ₹50 | Use code TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			ribbon: [
				{
					type: "PROMOTED",
				},
			],
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "cid=5701830~p=16~eid=00000185-9f7f-f12c-24f7-44c300221023",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "4.4 kms",
			hasSurge: false,
			sla: {
				restaurantId: "50887",
				deliveryTime: 30,
				minDeliveryTime: 30,
				maxDeliveryTime: 30,
				lastMileTravel: 4.400000095367432,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: true,
			avgRating: "4.1",
			totalRatings: 1000,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "46857",
			name: "Bakingo",
			uuid: "9fc2a242-8ba9-4683-8ca8-55809161d535",
			city: "4",
			area: "Shalimar Bagh",
			totalRatingsString: "500+ ratings",
			cloudinaryImageId: "t4krbxhzmffz1l2yxten",
			cuisines: ["Bakery", "Desserts", "Beverages", "Snacks"],
			tags: [],
			costForTwo: 30000,
			costForTwoString: "₹300 FOR TWO",
			deliveryTime: 25,
			minDeliveryTime: 25,
			maxDeliveryTime: 25,
			slaString: "25 MINS",
			lastMileTravel: 2.0999999046325684,
			slugs: {
				restaurant: "bakingo-shalimar-bagh-ashok-vihar",
				city: "delhi",
			},
			cityState: "4",
			address:
				"Property number SE-21, Ground Floor, Singhalpur EXTN., Shalimar Bagh ,  North West , Delhi-110088",
			locality: "Ashok Vihar",
			parentId: 3818,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "60% off",
				shortDescriptionList: [
					{
						meta: "60% off | Use MISSEDYOU",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "60% off up to ₹100 | Use code MISSEDYOU",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "60% OFF",
				shortDescriptionList: [
					{
						meta: "Use MISSEDYOU",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "60% off up to ₹100 | Use code MISSEDYOU",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "2 kms",
			hasSurge: false,
			sla: {
				restaurantId: "46857",
				deliveryTime: 25,
				minDeliveryTime: 25,
				maxDeliveryTime: 25,
				lastMileTravel: 2.0999999046325684,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "4.1",
			totalRatings: 500,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "607975",
			name: "PARATHA JUNCTION",
			uuid: "21b1751c-6c4e-4843-91a6-276b08f21282",
			city: "4",
			area: "Karol Bagh",
			totalRatingsString: "Too Few Ratings",
			cloudinaryImageId: "agdavoxeigohgqy5xtt5",
			cuisines: ["North Indian"],
			tags: [],
			costForTwo: 5000,
			costForTwoString: "₹50 FOR TWO",
			deliveryTime: 54,
			minDeliveryTime: 50,
			maxDeliveryTime: 60,
			slaString: "50-60 MINS",
			lastMileTravel: 12.300000190734863,
			slugs: {
				restaurant: "paratha-junction-karol-bagh-karol-bagh-2",
				city: "delhi",
			},
			cityState: "4",
			address:
				"3729, Ground Floor, Dariba Pan, Near, Railway Station, Ratan Lal Market, Kaseru Walan, Paharganj, New Delhi, Delhi 110055, India",
			locality: "Paharganj",
			parentId: 3467,
			unserviceable: false,
			veg: true,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: "distance",
						fee: 10600,
						message: "",
					},
					{
						name: "time",
						fee: 0,
						message: "",
					},
					{
						name: "special",
						fee: 0,
						message: "",
					},
				],
				totalFees: 10600,
				message: "",
				title: "Delivery Charge",
				amount: "10600",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 1,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "12.3 kms",
			hasSurge: false,
			sla: {
				restaurantId: "607975",
				deliveryTime: 54,
				minDeliveryTime: 50,
				maxDeliveryTime: 60,
				lastMileTravel: 12.300000190734863,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "IT_IS_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "--",
			totalRatings: 0,
			new: false,
		},
		subtype: "basic",
		scrubber: {
			value: "₹50 FOR TWO",
		},
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "640721",
			name: "Paratha Hub",
			uuid: "a34c1cb9-f83d-4336-a3de-33be5965383f",
			city: "4",
			area: "Rohini",
			totalRatingsString: "Too Few Ratings",
			cloudinaryImageId: "mj6bufjzvob4w5ith3us",
			cuisines: ["Indian", "Fast Food", "Beverages"],
			tags: [],
			costForTwo: 9900,
			costForTwoString: "₹99 FOR TWO",
			deliveryTime: 40,
			minDeliveryTime: 40,
			maxDeliveryTime: 40,
			slaString: "40 MINS",
			lastMileTravel: 5.5,
			slugs: {
				restaurant: "paratha-hub-rohini-rohini",
				city: "delhi",
			},
			cityState: "4",
			address:
				"G-9/99 Sector 16, Rohini Delhi, RITHALA, Rohini, North West , Delhi - 110089",
			locality: "Sector 16 G",
			parentId: 155386,
			unserviceable: false,
			veg: true,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "10% off",
				shortDescriptionList: [
					{
						meta: "10% off | Use TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "10% off up to ₹40 | Use code TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "10% OFF",
				shortDescriptionList: [
					{
						meta: "Use TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "10% off up to ₹40 | Use code TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			ribbon: [
				{
					type: "NEW",
				},
			],
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "5.5 kms",
			hasSurge: false,
			sla: {
				restaurantId: "640721",
				deliveryTime: 40,
				minDeliveryTime: 40,
				maxDeliveryTime: 40,
				lastMileTravel: 5.5,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "--",
			totalRatings: 0,
			new: true,
		},
		subtype: "basic",
		scrubber: {
			value: "₹99 FOR TWO",
		},
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "323927",
			name: "Kullhad - 100% Desi Chai",
			uuid: "6848c430-b672-439e-a2f8-cdc882803feb",
			city: "4",
			area: "Tri Nagar",
			totalRatingsString: "Too Few Ratings",
			cloudinaryImageId: "zf3lkiamwbs7jgzhpfi6",
			cuisines: ["Beverages"],
			tags: [],
			costForTwo: 9900,
			costForTwoString: "₹99 FOR TWO",
			deliveryTime: 37,
			minDeliveryTime: 37,
			maxDeliveryTime: 37,
			slaString: "37 MINS",
			lastMileTravel: 5.699999809265137,
			slugs: {
				restaurant: "kullhad---100%-desi-chai-ashok-vihar-ashok-vihar",
				city: "delhi",
			},
			cityState: "4",
			address:
				"2525/193, near Hanuman Mandir, Onkar Nagar A, Tota Ram Bazar, Ganeshpura, Tri Nagar, New Delhi, Delhi 110035, India",
			locality: "Ashok Vihar",
			parentId: 121719,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "50% off",
				shortDescriptionList: [
					{
						meta: "50% off | Use TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹100 | Use code TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "50% OFF",
				shortDescriptionList: [
					{
						meta: "Use TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹100 | Use code TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "5.6 kms",
			hasSurge: false,
			sla: {
				restaurantId: "323927",
				deliveryTime: 37,
				minDeliveryTime: 37,
				maxDeliveryTime: 37,
				lastMileTravel: 5.699999809265137,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "--",
			totalRatings: 0,
			new: false,
		},
		subtype: "basic",
		scrubber: {
			value: "₹99 FOR TWO",
		},
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "621810",
			name: "The Arrow Rasoi",
			uuid: "335a4db7-cd94-4644-bba4-97e3a17c098a",
			city: "4",
			area: "Rohini",
			totalRatingsString: "Too Few Ratings",
			cloudinaryImageId: "nnizmzephwdamljihapd",
			cuisines: ["North Indian", "Chinese", "Fast Food", "Snacks", "Thalis"],
			tags: [],
			costForTwo: 9900,
			costForTwoString: "₹99 FOR TWO",
			deliveryTime: 42,
			minDeliveryTime: 42,
			maxDeliveryTime: 42,
			slaString: "42 MINS",
			lastMileTravel: 5.699999809265137,
			slugs: {
				restaurant: "the-arrow-rasoi-rohini-rohini",
				city: "delhi",
			},
			cityState: "4",
			address:
				"I 6/91 Ram krishna marg rohini sec 16 west, BEGUM PUR, Rohini, North West , Delhi - 110089",
			locality: "BEGUM PUR",
			parentId: 370327,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "5.6 kms",
			hasSurge: false,
			sla: {
				restaurantId: "621810",
				deliveryTime: 42,
				minDeliveryTime: 42,
				maxDeliveryTime: 42,
				lastMileTravel: 5.699999809265137,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "--",
			totalRatings: 0,
			new: false,
		},
		subtype: "basic",
		scrubber: {
			value: "₹99 FOR TWO",
		},
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "93301",
			name: "sharma ji paratha wala delhi 6",
			uuid: "24c25f3e-2fe7-4e5c-b7a5-8d66ce02a67e",
			city: "4",
			area: "kamla nagar ",
			totalRatingsString: "50+ ratings",
			cloudinaryImageId: "dwaicawlm6vlbesmigqn",
			cuisines: ["North Indian"],
			tags: [],
			costForTwo: 9900,
			costForTwoString: "₹99 FOR TWO",
			deliveryTime: 44,
			minDeliveryTime: 44,
			maxDeliveryTime: 44,
			slaString: "44 MINS",
			lastMileTravel: 7.900000095367432,
			slugs: {
				restaurant: "sharma-ji-paratha-wala-delhi-6-delhi-india-tis-hazari",
				city: "delhi",
			},
			cityState: "4",
			address:
				"2761 gali ram roop 2nd floor, Near robin cenima maim bazaar sabji mandi, DELHI, CIVIL LINES, Central, Delhi - 110007",
			locality: "Civil Lines",
			parentId: 11465,
			unserviceable: false,
			veg: true,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "Free delight",
				shortDescriptionList: [
					{
						meta: "Free delight on orders above ₹99",
						discountType: "Freebie",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "Free delight on orders above ₹99",
						discountType: "Freebie",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "",
				shortDescriptionList: [
					{
						meta: "Free delight",
						discountType: "Freebie",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "Free delight on orders above ₹99",
						discountType: "Freebie",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 1,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "7.9 kms",
			hasSurge: false,
			sla: {
				restaurantId: "93301",
				deliveryTime: 44,
				minDeliveryTime: 44,
				maxDeliveryTime: 44,
				lastMileTravel: 7.900000095367432,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "IT_IS_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "4.3",
			totalRatings: 50,
			new: false,
		},
		subtype: "basic",
		scrubber: {
			value: "₹99 FOR TWO",
		},
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "10110",
			name: "Sita Ram Diwan Chand",
			uuid: "270d7250-c7a7-42a1-b52b-1570cffdf581",
			city: "4",
			area: "Pitam Pura",
			totalRatingsString: "500+ ratings",
			cloudinaryImageId: "ds5pkjzsjsvfxb2xhmsp",
			cuisines: ["North Indian", "Snacks", "Street Food"],
			tags: [],
			costForTwo: 10000,
			costForTwoString: "₹100 FOR TWO",
			deliveryTime: 24,
			minDeliveryTime: 24,
			maxDeliveryTime: 24,
			slaString: "24 MINS",
			lastMileTravel: 3,
			slugs: {
				restaurant: "sita-ram-diwan-chand-nsp",
				city: "delhi",
			},
			cityState: "4",
			address: "Shop 2, MD Market, Muni Maya Ram Jain Marg, MD Block, Pitampura",
			locality: "Muni Maya Ram Jain Marg",
			parentId: 3621,
			unserviceable: false,
			veg: true,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "50% off",
				shortDescriptionList: [
					{
						meta: "50% off | Use TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹100 | Use code TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "50% OFF",
				shortDescriptionList: [
					{
						meta: "Use TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹100 | Use code TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			ribbon: [
				{
					type: "PROMOTED",
				},
			],
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "cid=5654740~p=1~eid=00000185-a3d4-7506-29f7-37eb0022017b",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "3 kms",
			hasSurge: false,
			sla: {
				restaurantId: "10110",
				deliveryTime: 24,
				minDeliveryTime: 24,
				maxDeliveryTime: 24,
				lastMileTravel: 3,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: true,
			avgRating: "4.1",
			totalRatings: 500,
			new: false,
		},
		subtype: "basic",
		scrubber: {
			value: "₹100 FOR TWO",
		},
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "36270",
			name: "Bille Di hatti (Pitampura) ",
			uuid: "a7e53533-9300-46e7-9e6b-ba3278903701",
			city: "4",
			area: "Pitampura",
			totalRatingsString: "1000+ ratings",
			cloudinaryImageId: "xovqdwufznyil35jg602",
			cuisines: ["Street Food", "Snacks", "North Indian"],
			tags: [],
			costForTwo: 10000,
			costForTwoString: "₹100 FOR TWO",
			deliveryTime: 21,
			minDeliveryTime: 21,
			maxDeliveryTime: 21,
			slaString: "21 MINS",
			lastMileTravel: 3,
			slugs: {
				restaurant: "bille-di-hatti-pp-trade-centre-nsp",
				city: "delhi",
			},
			cityState: "4",
			address: "Rp 8 Pitampura new delhi -110034",
			locality: "RP Block, Pitampura",
			parentId: 4639,
			unserviceable: false,
			veg: true,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "FLAT125 off",
				shortDescriptionList: [
					{
						meta: "FLAT125 off | Use FLATDEAL",
						discountType: "Flat",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "FLAT125 off | Use FLATDEAL",
						discountType: "Flat",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "₹125 OFF",
				shortDescriptionList: [
					{
						meta: "Use FLATDEAL",
						discountType: "Flat",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "FLAT125 off | Use FLATDEAL",
						discountType: "Flat",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "3 kms",
			hasSurge: false,
			sla: {
				restaurantId: "36279",
				deliveryTime: 21,
				minDeliveryTime: 21,
				maxDeliveryTime: 21,
				lastMileTravel: 3,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "3.9",
			totalRatings: 1000,
			new: false,
		},
		subtype: "basic",
		scrubber: {
			value: "₹100 FOR TWO",
		},
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "611050",
			name: "GOLA JI PRANATHE WALE",
			uuid: "a546b16f-c342-42a1-b563-c0a58aa757ec",
			city: "4",
			area: "Ashok Vihar",
			totalRatingsString: "Too Few Ratings",
			cloudinaryImageId: "i08x3ukvxdsbdrr7cccq",
			cuisines: ["North Indian", "Beverages"],
			tags: [],
			costForTwo: 10000,
			costForTwoString: "₹100 FOR TWO",
			deliveryTime: 32,
			minDeliveryTime: 32,
			maxDeliveryTime: 32,
			slaString: "32 MINS",
			lastMileTravel: 2.299999952316284,
			slugs: {
				restaurant: "gola-ji-pranathe-wale-ashok-vihar-ashok-vihar",
				city: "delhi",
			},
			cityState: "4",
			address:
				"Adarsh Nagar Metro Station, Mool Chand Nagar, Adarsh Nagar, Delhi, 110033, India",
			locality: "Mool Chand Nagar",
			parentId: 363745,
			unserviceable: false,
			veg: true,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "2.2 kms",
			hasSurge: false,
			sla: {
				restaurantId: "611050",
				deliveryTime: 32,
				minDeliveryTime: 32,
				maxDeliveryTime: 32,
				lastMileTravel: 2.299999952316284,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "--",
			totalRatings: 0,
			new: false,
		},
		subtype: "basic",
		scrubber: {
			value: "₹100 FOR TWO",
		},
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "321440",
			name: "Drool Over Biryani",
			uuid: "13191f78-76bd-45a2-b373-80a75c2d10c4",
			city: "4",
			area: "Ashok Vihar",
			totalRatingsString: "20+ ratings",
			cloudinaryImageId: "djvp7p3jgavopld3p6ds",
			cuisines: ["Indian", "Street Food", "Biryani"],
			tags: [],
			costForTwo: 10000,
			costForTwoString: "₹100 FOR TWO",
			deliveryTime: 33,
			minDeliveryTime: 33,
			maxDeliveryTime: 33,
			slaString: "33 MINS",
			lastMileTravel: 4.599999904632568,
			slugs: {
				restaurant: "pav-bhaji-junction-sohna-road-sohna-road",
				city: "delhi",
			},
			cityState: "4",
			address: "Plot No 1 First Floor, GT Karnal Road, Industrial Area.",
			locality: "Azadpur",
			parentId: 314404,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "4.5 kms",
			hasSurge: false,
			sla: {
				restaurantId: "321440",
				deliveryTime: 33,
				minDeliveryTime: 33,
				maxDeliveryTime: 33,
				lastMileTravel: 4.599999904632568,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "2.7",
			totalRatings: 20,
			new: false,
		},
		subtype: "basic",
		scrubber: {
			value: "₹100 FOR TWO",
		},
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "580401",
			name: "ChaCha ke Pranthe",
			uuid: "227dcd5a-8e40-429b-b678-e66957af08f9",
			city: "4",
			area: "Ashok Vihar",
			totalRatingsString: "Too Few Ratings",
			cloudinaryImageId: "varbd25fgtiub9xjuqxw",
			cuisines: ["North Indian", "Chinese", "Biryani", "Snacks"],
			tags: [],
			costForTwo: 10000,
			costForTwoString: "₹100 FOR TWO",
			deliveryTime: 40,
			minDeliveryTime: 40,
			maxDeliveryTime: 40,
			slaString: "40 MINS",
			lastMileTravel: 4.400000095367432,
			slugs: {
				restaurant: "chacha-ke-pranthe-ashok-vihar-ashok-vihar",
				city: "delhi",
			},
			cityState: "4",
			address:
				"Shop no. 31-B, Murga Market, J Block, Phase 1, DDA Market, Ashok Vihar",
			locality: "Dda Market",
			parentId: 347379,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "4.4 kms",
			hasSurge: false,
			sla: {
				restaurantId: "580401",
				deliveryTime: 40,
				minDeliveryTime: 40,
				maxDeliveryTime: 40,
				lastMileTravel: 4.400000095367432,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "--",
			totalRatings: 0,
			new: false,
		},
		subtype: "basic",
		scrubber: {
			value: "₹100 FOR TWO",
		},
	},
];

export const carouselOptions = [
	{
		type: "carouselElement",
		subtype: "image",
		data: {
			bannerId: 619141,
			creativeId: "rng/md/carousel/production/zpkkdkmvlj5cuvqbc50t",
			type: "restaurantCollectionV2",
			link: "56413",
			cityId: 0,
			restaurantUuid: "",
			restaurantParentId: "0",
			thirdPartyVendor: "",
			thirdPartyAddress: false,
		},
	},
	{
		type: "carouselElement",
		subtype: "image",
		data: {
			bannerId: 304827,
			creativeId: "rng/md/carousel/production/awurei8ypqkafoqay9ym",
			type: "restaurantCollectionV2",
			link: "47670",
			cityId: 0,
			restaurantUuid: "",
			restaurantParentId: "0",
			thirdPartyVendor: "",
			thirdPartyAddress: false,
		},
	},
	{
		type: "carouselElement",
		subtype: "image",
		data: {
			bannerId: 607193,
			creativeId: "rng/md/carousel/production/s5ug2key6e2sptaxku5v",
			type: "restaurantCollectionV2",
			link: "56410",
			cityId: 0,
			restaurantUuid: "",
			restaurantParentId: "0",
			thirdPartyVendor: "",
			thirdPartyAddress: false,
		},
	},
	{
		type: "carouselElement",
		subtype: "image",
		data: {
			bannerId: 607195,
			creativeId: "rng/md/carousel/production/ifi2lbzxeu1hvsqrsip3",
			type: "restaurantCollectionV2",
			link: "56421",
			cityId: 0,
			restaurantUuid: "",
			restaurantParentId: "0",
			thirdPartyVendor: "",
			thirdPartyAddress: false,
		},
	},
];
